# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
