# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20180820_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
